sudo: required
language: node_js
node_js:
  - "9"

install:
  - npm i -g lix
  - lix download
  - lix run travix install

script:
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  #- lix run travix flash -D flash-exit -D reporter=buddy.reporting.TraceReporter
  - lix run travix java -D jvm
  - lix run travix cpp
  - lix run travix php
